// Hard-coded list of fun facts. Add or edit freely.
const FUN_FACTS = [
    "Honey never spoils. Archaeologists have found 3,000-year-old honey in Egyptian tombs that's still edible.",
    "Octopuses have three hearts, nine brains, and blue blood.",
    "A group of flamingos is called a 'flamboyance'.",
    "Bananas are berries, but strawberries are not.",
    "The Eiffel Tower can grow more than 15 cm taller during hot summer days due to thermal expansion.",
    "Sharks existed before trees did.",
    "Wombat poop is cube-shaped.",
    "There are more stars in the universe than grains of sand on all of Earth's beaches.",
    "A day on Venus is longer than a year on Venus.",
    "Cows have best friends and get stressed when separated from them.",
    "The inventor of the Frisbee was turned into a Frisbee after he died — his ashes were molded into discs.",
    "Sea otters hold hands while sleeping so they don't drift apart.",
    "The unicorn is the national animal of Scotland.",
    "A bolt of lightning is about five times hotter than the surface of the Sun.",
    "Humans share about 60% of their DNA with bananas.",
    "The shortest war in history lasted 38 to 45 minutes (Anglo-Zanzibar War, 1896).",
    "Napoleon was once attacked by a horde of bunnies.",
    "A single strand of spaghetti is called a 'spaghetto'.",
    "Your stomach gets a new lining every 3–4 days to keep it from digesting itself.",
    "Butterflies taste with their feet.",
    "There's enough DNA in your body to stretch from the Sun to Pluto and back — 17 times.",
    "The Great Wall of China is not visible from space with the naked eye — that's a myth.",
    "Hot water freezes faster than cold water under certain conditions (the Mpemba effect).",
    "Slugs have four noses.",
    "The dot over a lowercase 'i' or 'j' is called a tittle.",
    "A cloud weighs around a million tonnes. A cloud typically has a volume of around 1km3 and a density of around 1.003kg per m3 – that's a density that’s around 0.4 per cent lower than the air surrounding it (this is how they are able to float).",
    "Identical twins don’t have the same fingerprints. You can’t blame your crimes on your twin, after all. This is because environmental factors during development in the womb (umbilical cord length, position in the womb, and the rate of finger growth) impact your fingerprint.",
    "Earth’s rotation is changing speed. It's actually slowing. This means that, on average, the length of a day increases by around 1.8 seconds per century. 600 million years ago a day lasted just 21 hours.",
    "Leftover pasta has extra health benefits. That's because it contains more resistant starch than fresh pasta, thanks to the effect of cooking and cooling on the pasta starch's structure. Resistant starch has been linked to improved blood sugar control and better gut health.",
    "Parents in the US consistently rank as the world's unhappiest. Happiness and wellbeing surveys are far from an exact science, but parents in the US report being far less happy than non-parents. In contrast, Portuguese parents seem to be slightly happier than non-parents. There are plenty of reasons why.",
    "A thunderstorm called Hector the Convector arrives everyday at 3pm. Most thunderstorms are unpredictable, but not Hector. Thanks to a microclimate over the Tiwi Islands (off the coast of northern Australia), Hector arrives everyday at 3pm, from September through to March. He's also huge, regularly reaching more than 19km (12 miles) high.",
    "Earlobes have no biological purpose. While they are rich in nerve endings and may play a role in social bonding, many scientists argue that earlobes don’t have any true biological purpose.",
    "When you're reading – even silently – the muscles of your mouth, tongue and larynx activate. This process is called 'subvocalisation'. We're essentially still sounding out the words in our heads to decode them, even when we're not speaking them out loud.",
    "The largest piece of fossilised dinosaur poo discovered is over 30cm long and over two litres in volume. Believed to be a Tyrannosaurus rex turd, the fossilised dung (also named a 'coprolite') is helping scientists better understand what the dinosaur ate.",
    "Mars isn’t actually round. Unlike any other rocky planet in the Solar System, Mars is actually shaped like a rugby ball, but with different sizes along all three axes.",
    "There’s no such thing as zero-calorie foods. Even low-calorie foods, such as celery and watercress, contain more energy than the body needs to process them.",
    "Around 8–10 per cent of people grind their teeth at night. The process is called sleep bruxism, and most people aren't even aware they're doing it.",
    "The Universe's average colour is called 'Cosmic latte'. In a 2002 study, astronomers found that the light coming from galaxies averaged into a beige colour that’s close to white.",
    "Water might not be wet. This is because most scientists define wetness as a liquid’s ability to maintain contact with a solid surface, meaning that water itself is not wet, but can make other objects wet.",
    "Most people stroke cats the wrong way. Research shows they often just tolerate it for the food and attention. The safest spots? Under the chin, cheeks and base of the ears. The worst? Their belly and the base of their tail – touch there and you’re more likely to annoy them than bond with them.",
    "Newborn babies don't actually see in black and white. Their colour vision is limited, but they can detect some intense colours, especially red. This is because the eyes' cone cells, which detect colour, aren't fully mature at birth.",
    "The raw ingredients of a human body would cost over £116,000. But if you’re prepared to do the refining yourself, a body could cost a lot less – under £100 in fact.",
    "All the world’s bacteria stacked on top of each other would stretch for 10 billion light-years. Together, Earth's 0.001mm-long microbes could wrap around the Milky Way over 20,000 times.",
    "Wearing a tie can reduce blood flow to the brain by 7.5 per cent. A study in 2018 found that wearing a necktie can reduce the blood flow to your brain by up to 7.5 per cent, which can make you feel dizzy, nauseous and cause headaches. They can also increase the pressure in your eyes if on too tight and are great at carrying germs.",
    "The fear of long words is called Hippopotomonstrosesquippedaliophobia. The 36-letter word was first used by the Roman poet Horace in the first century BCE to criticise those writers with an unreasonable penchant for long words. It was American poet Aimee Nezheukumatathil, possibly afraid of their own surname, who coined the term as we know it in 2000.",
    "The world’s oldest dog lived to 29.5 years old. While the median age a dog reaches tends to be about 10-15 years, one Australian cattle dog, ‘Bluey’, survived to the ripe old age of 29.5.",
    "Leftover pasta has extra health benefits. That's because it contains more resistant starch than fresh pasta, thanks to the effect of cooking and cooling on the pasta starch's structure. Resistant starch has been linked to improved blood sugar control and better gut health.",
    "Parents in the US consistently rank as the world's unhappiest. Happiness and wellbeing surveys are far from an exact science, but parents in the US report being far less happy than non-parents. In contrast, Portuguese parents seem to be slightly happier than non-parents. There are plenty of reasons why.",
    "A thunderstorm called Hector the Convector arrives everyday at 3pm. Most thunderstorms are unpredictable, but not Hector. Thanks to a microclimate over the Tiwi Islands (off the coast of northern Australia), Hector arrives everyday at 3pm, from September through to March. He's also huge, regularly reaching more than 19km (12 miles) high.",
    "Earlobes have no biological purpose. While they are rich in nerve endings and may play a role in social bonding, many scientists argue that earlobes don’t have any true biological purpose. ",
    "When you're reading – even silently – the muscles of your mouth, tongue and larynx activate. This process is called 'subvocalisation'. We're essentially still sounding out the words in our heads to decode them, even when we're not speaking them out loud.",
    "The largest piece of fossilised dinosaur poo discovered is over 30cm long and over two litres in volume. Believed to be a Tyrannosaurus rex turd, the fossilised dung (also named a 'coprolite') is helping scientists better understand what the dinosaur ate.",
    "Mars isn’t actually round. Unlike any other rocky planet in the Solar System, Mars is actually shaped like a rugby ball, but with different sizes along all three axes.",
    "There’s no such thing as zero-calorie foods. Even low-calorie foods, such as celery and watercress, contain more energy than the body needs to process them. ",
    "Around 8–10 per cent of people grind their teeth at night. The process is called sleep bruxism, and most people aren't even aware they're doing it.",
    "The Universe's average colour is called 'Cosmic latte'. In a 2002 study, astronomers found that the light coming from galaxies averaged into a beige colour that’s close to white.",
    "Water might not be wet. This is because most scientists define wetness as a liquid’s ability to maintain contact with a solid surface, meaning that water itself is not wet, but can make other objects wet.",
    "Most people stroke cats the wrong way. Research shows they often just tolerate it for the food and attention. The safest spots? Under the chin, cheeks and base of the ears. The worst? Their belly and the base of their tail – touch there and you’re more likely to annoy them than bond with them.",
    "Newborn babies don't actually see in black and white. Their colour vision is limited, but they can detect some intense colours, especially red. This is because the eyes' cone cells, which detect colour, aren't fully mature at birth.",
    "The raw ingredients of a human body would cost over £116,000. But if you’re prepared to do the refining yourself, a body could cost a lot less – under £100 in fact.",
    "All the world’s bacteria stacked on top of each other would stretch for 10 billion light-years. Together, Earth's 0.001mm-long microbes could wrap around the Milky Way over 20,000 times.",
    "Wearing a tie can reduce blood flow to the brain by 7.5 per cent. A study in 2018 found that wearing a necktie can reduce the blood flow to your brain by up to 7.5 per cent, which can make you feel dizzy, nauseous and cause headaches. They can also increase the pressure in your eyes if on too tight and are great at carrying germs.",
    "The fear of long words is called Hippopotomonstrosesquippedaliophobia. The 36-letter word was first used by the Roman poet Horace in the first century BCE to criticise those writers with an unreasonable penchant for long words. It was American poet Aimee Nezheukumatathil, possibly afraid of their own surname, who coined the term as we know it in 2000.",
    "The world’s oldest dog lived to 29.5 years old. While the median age a dog reaches tends to be about 10-15 years, one Australian cattle dog, ‘Bluey’, survived to the ripe old age of 29.5.",
    "The world’s oldest cat lived to 38 years and three days old. Creme Puff was the oldest cat to ever live.",
    "We've only explored 0.001 per cent of the ocean floor. We have more detailed maps of the Moon than the deep seafloor. Out of a total area of more than 335 million square kilometres (around 129.3 million square miles), scientists have explored less than 0.001 per cent – roughly the same as Rhode Island, the smallest US state.",
    "Mount Everest isn't the tallest mountain on Earth. Mauna Kea and Mauna Loa in Hawaii, the twin volcanoes, are taller than Mount Everest as 4.2km of their height is submerged underwater. The twin volcanoes measure a staggering 10.2km in total, compared to Everest’s paltry 8.8km.",
    "Our solar system has a wall. The heliopause – the region of space in which solar wind isn’t hot enough to push back the wind of particles coming from distant stars – is often considered the “boundary wall” of the Solar System and interstellar space.",
    "Most maps of the world are wrong. On most maps, the Mercator projection – first developed in 1569 – is still used. This method is wildly inaccurate and makes Alaska appear as large as Brazil and Greenland 14 times larger than it actually is. For a map to be completely accurate, it would need to be life-size and round, not flat.",
    "The Moon is gradually drifting away from Earth. But it's not going anywhere fast. The distance between it and us is growing by around 3cm (1.2in) every year.",
    "Comets smell like rotten eggs. A comet smells like rotten eggs, urine, burning matches, and… almonds. Traces of hydrogen sulphide, ammonia, sulphur dioxide, and hydrogen cyanide were all found in the makeup of the comet 67P/Churyumove-Gerasimenko. Promotional postcards were even commissioned in 2016 carrying the pungent scent of a comet.",
    "Earth’s poles are moving. This magnetic reversal of the North and South Pole has happened 171 times in the past 71 million years. We’re overdue a flip. It could come soon, as the North Pole is moving at around 55 kilometres per year, an increase over the 15km per year up until 1990.",
    "You can actually die laughing. And a number of people have, typically due to intense laughter causing a heart attack or suffocation. Comedy shows should come with a warning.",
    "Chainsaws were first invented for childbirth. It was developed in Scotland in the late 18th Century to help aid and speed up the process of symphysiotomy (widening the pubic cartilage) and removal of disease-laden bone during childbirth. It wasn’t until the start of the 20th Century that we started using chainsaws for woodchopping.",
    "Cats prefer to sleep on their left. This preference may help them engage the right hemisphere of their brains, so they can better visually process their environments and dodge potential danger upon waking.",
    "You don’t actually lose most of your heat through your head. Your face, head and chest are more sensitive to temperature changes, but this myth isn’t entirely true. In reality, covering any part of the body helps prevent heat loss in the same way. ",
    "The T.rex likely had feathers. Scientists in China discovered Early Cretaceous period tyrannosaur skeletons that were covered in feathers. If the ancestors of the T. rex had feathers, the T. rex probably did, too.",
    "Football teams wearing red kits play better. The colour of your clothes can affect how you’re perceived by others and change how you feel. A review of football matches in the last 55 years, for example, showed that teams wearing a red kit consistently played better in home matches than teams in any other colour.",
    "When you cut a worm in two, it regenerates. That said, this only works if it’s cut widthways – and not all will. Earthworms can regrow their tails, and the planarian flatworm can regrow its whole body from a tiny sliver of tissue. ",
    "Wind turbines kill between 10,000 and 100,000 birds each year in the UK. Interestingly, painting one of the blades of a wind turbine black can reduce bird deaths by 70 per cent.",
    "Board games can reduce your risk of dementia. Monopoly, Scrabble, Risk – take your pick. Board games can keep your brain healthy as you age, protecting your brain from cognitive decline and reducing your risk of neurodegenerative diseases such as dementia.",
    "Sound can be minus decibels. The quietest place on Earth is Microsoft’s anechoic chamber in Redmond, WA, USA, at -20.6 decibels. These anechoic chambers are built out of heavy concrete and brick and are mounted on springs to stop vibrations from getting in through the floor.",
    "A horse normally has more than one horsepower. A study in 1993 showed that the maximum power a horse can produce is 18,000W, around 24 horsepower.",
    "About 60 per cent of your body is water. Fluid retention – caused by what you've eaten or hormonal fluctuations – can is one of the reasons why your weight might fluctuate by around 0.5kg–2kg (1–5lbs) from day to day.",
    "In 1912, a man invented a human flying suit, jumped off the Eiffel Tower, and fell to his death. The inventor was called Franz Reichelt and was a tailor by trade. He wanted to design a suit that could be used as a parachute for pilots, in the early days of human plane travel. After testing the suit on a number of dummies, Reichelt was so confident that he decided to try it out himself, and jumped off the lower level of the Eiffel Tower. It didn't go well.",
    "Orcas wear other animals as hats. Scientists have observed dolphins playing catch with pufferfish and octopuses, and orcas wearing dead fish as hats. No one knows why.",
    "Deaf people are known to use sign language in their sleep. A case study of a 71-year-old man with rapid eye movement disorder and a severe hearing impairment showed him using fluent sign language in his sleep, with researchers able to get an idea of what he was dreaming about thanks to those signs.",
    "Pythons can swallow people whole. It's rare, but does happen. Indonesia seems to be a particular hotspot – for example, one 45-year-old woman was discovered fully clothed inside a bloated, 5m-long (16ft) snake.",
    "Finland is the happiest country on Earth. According to the World Happiness Report, it has been for six years in a row. It’s not really surprising, given that Finland is the home of Santa Claus, reindeer and one sauna for every 1.59 people.",
    "Hippos can’t swim. Hippos really do have big bones, so big and dense, in fact, that they’re barely buoyant at all. They don’t swim and instead perform a slow-motion gallop on the riverbed or on the sea floor. In fact, hippos can even sleep underwater, thanks to a built-in reflex that allows them to bob up, take a breath, and sink back down without waking.",
    "The Moon looks upside down in the Southern Hemisphere. Compared to the Northern Hemisphere, anyway. This means that the ‘Man in the Moon’ is upside down in the Southern Hemisphere and looks more like a rabbit.",
    "You can yo-yo in space. In 2012, NASA astronaut Don Pettit took a yo-yo on board the International Space Station and demonstrated several tricks. It works because a yo-yo mainly relies on the laws of conservation of angular momentum to perform tricks, which, provided you keep the string taut, apply in microgravity too.",
    "Not only plants photosynthesise. Algae (which are not plants) and some other organisms – including sea slugs and pea aphids – contain chlorophyll and can also take sunlight and turn it into an energy source.",
    "You can be heavily pregnant and not realise. Cryptic pregnancies aren’t that uncommon, with 1 in 500 not recognised until at least halfway through and 1 in 2,500 not known until labour starts.",
    "Bacteria on your skin cause your itches. Specifically, bacteria known as Staphylococcus aureus can release a chemical that activates a protein in our nerves. This sends a signal from our skin to our brains, which our brain perceives as an itch.",
    "Polar bears aren’t actually white. Surprisingly, underneath all their white fur, polar bears actually have jet-black skin. ",
    "Starfish don’t have bodies. Along with other echinoderms (think sea urchins and sand dollars), their entire bodies are technically classed as heads. ",
    "Somebody has been constipated for 45 days. In 2013, an unfortunate Indian woman had to undergo surgical removal of a faecal mass as large as a football.",
    "You travel 2.5 million km a day around the Sun without realising. The Earth’s orbit travels around 2.5 million kilometres with respect to the Sun’s centre, and around 19 million km with respect to the centre of the Milky Way.",
    "Fish form orderly queues in emergencies. When evacuating through narrow spaces in sketchy situations, schools of neon tetra fish queue so that they don’t collide or clog up the line. Scientists interpreted this behaviour as showing that fish can respect social rules even in emergency situations, unlike us humans. ",
    "There are more bacterial cells in your body than human cells. The average human is around 56 per cent bacteria. This was discovered in a 2016 study and is far less than the earlier estimates of 90 per cent. As bacteria are so light, however, by weight, each person is over 99.7 per cent human.",
    "Most ginger cats are male. There are roughly three ginger male cats to one ginger female. This is because the ginger gene is found on the X chromosome, meaning female cats would require two copies of the gene to become ginger whilst males only need one.",
    "Your nails grow faster in hot summer. This is probably due to increased blood supply to the fingertips. It could also be because you’re less stressed while on holiday so less likely to gnaw away at ‘em.",
    "The Bermuda Triangle is no more hazardous than any other busy ocean route. The mystery of this patch of sea gained legendary status in the 20th century, but the number of incidents in the Bermuda Triangle isn’t significantly higher than in any other part of the ocean.",
    "Insects can fly up to 3.25km above sea level, at least. Alpine bumblebees have been found living as high up as 3.25km above sea level and could even fly in lab conditions that replicate the air density and oxygen levels at 9km – that's just higher than Mount Everest.",
    "There’s a planet mostly made from diamond. Called 55 Cancri e, it's around twice the size of Earth and some 40 light-years away from us within the Cancer constellation.",
    "In the deep sea, male anglerfish don’t just mate – they fuse. The tiny males bite onto a much larger female and gradually dissolve into her body, leaving behind little more than a living sack of sperm she can use whenever she wants to lay eggs.",
    "There’s a condition in which your body can brew alcohol. Auto-brewery syndrome is a very rare condition which occurs when certain bacteria and yeasts in the gut break down carbohydrates into ethanol.",
    "It’s possible for two lucid dreamers to communicate mid-dream. Inter-brain neural synchronisation has been observed between people who are both asleep.  ",
    "It’s surprisingly easy to escape quicksand. Quicksand’s density is higher than that of the human body, making it impossible to sink completely. To escape quicksand, sit or lie back, try to keep your arms up and out of the quicksand, and slowly wiggle your legs side-to-side or back-and-forth. ",
    "A penguin can reach depths of 550m in one dive. Typically, emperor penguins (the deepest-diving penguins) plunge to 100-200m, but the deepest penguin dive on record was more than 550m.  ",
    "Animals can be allergic to humans. Animals can be allergic to our dead skin cells – dander. These allergic reactions can be just like ours, too, including breathing difficulties and skin irritation.",
    "Being bored is actually a 'high arousal state' physiologically. This is because when you're bored your heart rate increases.",
    "Our immune systems can detect bad bacteria from good. The immune system detects pathogen patterns through receptors and will mount an attack. Simultaneously, it will cooperate with microbes and beneficial bacteria. ",
    "Platypuses sweat milk. This is because it doesn't have teats. Milk appears as sweat on a platypus, but it's an aquatic mammal so it doesn't actually sweat at all.",
    "LEGO bricks withstand compression better than concrete. An ordinary plastic LEGO brick is able to support the weight of 375,000 other bricks before it fails. This, theoretically, would let you build a tower nearing 3.5km in height. Scaling this up to house-size bricks, however, would cost far too much.",
    "Martial artists who smile before the start of a match are more likely to lose. This could be as a smile can convey fear or submissiveness.",
    "It's almost impossible to get too much sugar from fresh fruit. While the sugar in fruit is mostly fructose and glucose (fructose is what's converted into fat in your body), you can't get too much sugar from fresh fruit. Fresh fruit contains a lot of fibre and water which slows down your digestion and makes you feel full.",
    "You don't like the sound of your own voice because of the bones in your head. This may be because the bones in our head make our voice sound deeper.",
    "A rainbow on Venus is called a glory. Appearing as a series of coloured concentric rings, these are caused by the interference of light waves within droplets, rather than the reflection, refraction and dispersion of light that makes a rainbow.",
    "Protons look like peanuts, rugby balls, bagels, and spheres. Protons come in all different shapes and sizes, with their appearance changing based on the speed of smaller particles within them: Quarks.",
    "Mirrors facing each other don't produce infinite reflections. Each reflection will be darker than the last and eventually fade into invisibility. Mirrors absorb a fraction of the energy of the light striking them. The total number of reflections mirrors can produce? A few hundred.",
    "There might be a cure for 'evil'. Well, a cure for psychopathy, anyway. Psychologists argue that aspects of psychopathy can be 'cured' by cognitive behavioural therapy, which is said to reduce violent offences by those with the condition. Preliminary research suggests that computer-based cognitive training could help a psychopath experience empathy and regret, too.",
    "All mammals get goosebumps. When your hair stands on end, tiny muscles contract at each hair's base which distorts the skin to create goosebumps. This process is called piloerection and is present in all mammals. Hair or fur is used to trap an insulating air layer.",
    "Football players spit so much because exercise increases the amount of protein in saliva. When you exercise, the amount of protein secreted into the saliva increases. A protein mucus named MUC5B makes your saliva thicker when you're exercising which makes it more difficult to swallow so we tend to spit more. It may occur during exercise because we breathe through our mouths more. MUC5B could activate to stop our mouths from drying out, therefore.",
    "Some animals display autistic-like traits. Autistic traits in animals include a tendency toward repetitive behaviour and atypical social habits.",
    "The biggest butterfly in the world has a 31cm wingspan. It belongs to the Queen Alexandra's Birdwing butterfly, which you can find in the forests of the Oro Province, in the east of Papua New Guinea.",
    "You remember more dreams when you sleep badly. Research suggests that if you sleep badly and wake up multiple times throughout the night you will be more likely to recall the content of any dreams you had. You are also more likely to remember a dream when woken from one.",
    "You could sweat when you're anxious to alert others. One theory suggests we've evolved to sweat whilst anxious to alert the brains of other people around us so they are primed for whatever it is that's making us anxious. Brain scans have revealed that when you sniff the sweat of a panic-induced person, regions of the brain that handle emotional and social signals light up. When you're anxious your sympathetic nervous system releases hormones including adrenaline, which activates your sweat glands.",
    "A lightning bolt is five times hotter than the surface of the Sun. The charge carried by a bolt of lightning is so intense that it has a temperature of 30,000°C (54,000°F).",
    "The longest anyone has held their breath underwater is over 24.5 minutes. The world record for breath-holding underwater was achieved by Croatian Budimir Šobat on 27 March 2021, who held his breath for a total of 24 minutes and 37 seconds. On average, a human can hold their breath between 30-90 seconds.",
    "The Moon is shrinking. But only very slightly – by about 50m (164ft) in radius over the last several hundred million years. Mysterious seismic activity, known as moonquakes, could be to blame.",
    "Dogs tilt their heads when you speak to them to better pinpoint familiar words. Your dog is tilting its head when you speak to it to pinpoint where noises are coming from more quickly. This is done to listen out more accurately for familiar words such as 'walkies' and helps them to better understand the tone of your voice. If a dog doesn't tilt its head that often (as those with shorter muzzles might), it's because it relies less on sound and more on sight.",
    "If the Earth doubled in size, trees would immediately fall over. This is because surface gravity would be doubled. It would also mean dog-size and larger animals would not be able to run without breaking a leg.",
    "Mercury, not Venus, is the closest planet to Earth on average. On average, Mercury is 1.04 astronomical units (AU) away from Earth compared to the 1.14 AU average distance between Earth and Venus. One AU is equal to the average distance between the Earth and the Sun. Venus still comes closest to Earth as part of its orbit around the Sun, however.",
    "Flamingoes aren’t born pink. They actually come into the world with grey/white feathers and only develop a pinkish hue after starting a diet of brine shrimp and blue-green algae. ",
    "You can smell ants. Many species of ants release strong-smelling chemicals when they’re angry, threatened or being squished. Trap-jaw ants release a chocolatey smell when annoyed, while citronella ants earn their name from the lemony odour they give off.",
    "People who eat whatever they want and stay slim have a slow metabolism, not fast. A skinny person tends to have less muscle mass than others, meaning their basal metabolic rate (BMR) is lower than those of a high muscle mass – this gives them a slow metabolism, not a fast one.",
    "There’s a scientist who willingly let insects sting him to find out which hurt the most. Justin Schmidt turned his own body into a research tool to create the Schmidt Pain Scale – and discovered the South American bullet ant delivers the most excruciating sting of all, describing it as like being shot.",
    "Earth is 4.54 billion years old. Using radiometric dating, scientists have discovered that the Earth is 4.54 billion years old (give or take 50 million years). This makes our planet half the age of the Milky Way Galaxy (11-13 billion years old) and around a third of the age of the Universe (10-15 billion years old).",
    "It’s actually fine to drink alcohol on (most) antibiotics. It’s unlikely that drinking alcohol in moderation will cause a big problem if you’re taking a common antibiotic (although there are exceptions, particularly metronidazole).",
    "Electrons might live forever. Scientists have estimated the minimum lifetime of the electron is about 6.6 × 1028 years – this is 66,000 ‘yottayears’. Since this is about 5 quintillion times the age of the Universe, even if electrons don’t live forever, they may as well do!",
    "Beavers don't actually live in dams. Technically, beavers live in a lodge that they build behind a dam, within a deep pool of water.",
    "The average dinosaur lifespan was surprisingly small. The Tyrannosaurus rex, for example, reached full size between 16-22 years old and lived up until 27-33. The largest dinosaurs such as the Brontosaurus and Diplodocus tended to live up to between 39-53 years old, maybe reaching the heights of 70.",
    "Someone left a family photo on the Moon. When Apollo 16 astronaut Charles Duke landed on the Moon in 1972, he decided to leave behind a photo of him, his two sons and his wife. The photo remains on the Moon to this day. ",
    "It rains methane on Saturn’s largest moon. Titan is the only moon in our Solar System with a dense atmosphere and the only body except Earth with liquid rivers, lakes and seas fed by rainfall. This rainfall isn’t water, though; it's liquid methane.",
    "Giraffes hum to communicate with each other. It’s thought that the low-frequency humming could be a form of ‘contact call’ between individuals who have been separated from their herd, helping them to find each other in the dark. Some researchers think they sleep talk too.",
    "Glass sponges can live for 15,000 years. This makes them one of the longest-living organisms on Earth. The immortal jellyfish, however, could theoretically live forever (but scientists aren’t sure)",
    "You have a 50 per cent chance of sharing a birthday with a friend. In any group of 23 people, two people will share a birthday, according to the maths. To find the probability of everyone in the group having a unique birthday, multiply all 23 probabilities together, giving 0.493. So the probability of a shared birthday is 1 - 0.493 = 0.507, or 50.7 per cent.",
    "Murder rates rise in summer. Ever feel angry or in a bad mood when the weather is hot? Well, you’re not alone. Violent crime goes up in hotter weather, and in the US, murder rates reportedly rise by 2.7 per cent over the summer.",
    "'New car smell' is a mix of over 200 chemicals. These include the sickly-sweet, toxic hydrocarbons benzene and toluene.",
    "‘Sea level’ isn’t actually level. As the strength of the force generated by the Earth’s spin is strongest at the equator, the average sea level bulges outward there, putting it further from the centre of the Earth than at the poles. Differences in the strength of the Earth’s gravity at different points also cause variation.",
    "You inhale 50 potentially harmful bacteria every time you breathe. Thankfully, your immune system is working hard all the time, so virtually all of these are promptly destroyed without you feeling a thing. Phew.",
    "You can see stars as they were 4,000 years ago with the naked eye. Without a telescope, all the stars we can see lie within about 4,000 light-years of us. That means at most you’re seeing stars as they were 4,000 years ago, around when the pyramids were being built in Egypt. ",
    "Plants came before seeds. According to the fossil record, early plants resembled moss and reproduced with single-celled spores. Multicellular seeds didn’t evolve for another 150 million years.",
    "Our dead cells are eaten by other cells in our body. Don’t worry; it’s meant to happen. When cells inside your body die, they’re scavenged by phagocytes – white blood cells whose job it is to digest other cells.",
    "Smells can pass through liquid. Please don’t try smelling underwater (your nose will not appreciate it), but smell does protrude through liquid. ",
    "Bats aren’t blind. Despite the famous idiom, bats can indeed see, but they still use their even more famous echolocation to find prey. ",
    "Hibernating animals don’t dream. Sleep is a more physiologically ‘active’ state than hibernation, which requires animals to substantially reduce all activities to conserve energy. There’s simply not enough brain activity while an animal is hibernating to enable dreaming. The only exception to this rule is the fat-tailed lemur. ",
    "Pine trees can tell if it's about to rain. Next time you see a pine cone, take a close look. If it’s closed, that’s because the air is humid, which can indicate rain is on its way. ",
    "You can’t fold a piece of A4 paper more than eight times. As the number of layers doubles each time, the paper rapidly gets too thick and too small to fold. The current world paper-folding record belongs to California high school student Britney Gallivan, who in 2002 managed to fold a 1.2km-long piece of tissue paper 12 times.",
    "The sharpest teeth in history didn’t belong to sharks or even dinosaurs. They came from conodonts – tiny eel-like creatures that lived 500 to 200 million years ago. Their tooth tips were just two micrometres wide, about 1/20th the width of a human hair, making them the sharpest ever measured.",
    "Laughing came before language. How do we know? Some researchers tickled baby apes, which, beyond being adorable, showed that they share the same structure as ours and likely arose in our common ancestors millions of years ago. Language came about much later. ",
    "The fastest jet in the world can fly almost 10 times the speed of sound (11,854km/h). The fastest jet is NASA’s X-43 experimental plane, three of which were built in total. The design meant that they had to be dropped from a Boeing B-52 in order to fly. ",
    "South Koreans have the lowest bad cholesterol levels in the world (and surprisingly, the US has one of the lowest). This is down to the Korean diet that’s rich in fermented foods and legumes, and low in saturated fat.",
    "Humans might be able to communicate through dreams. They need some help to do so, though – a company claims to have made it work while two people were lucid dreaming.",
    "Your cat sits on your laptop because it smells of you, not because it’s warm. More to the point, it’s trying to replace your smell with its own, because it owns you.",
    "Vultures make nests out of sandals and crossbows – or at least bearded vultures who lived in Spain hundreds of years ago did. They were definitely nature’s weirdest hoarders.",
    "The largest organ in the human body was only discovered in the past 10 years. That’s according to some scientists, anyway. It’s called the interstitium, and most of us don’t know we have one.",
    "Reptiles’ wee is solid. Or in some cases, a bit like a paste. It’s actually an evolutionary tactic – and some people think we humans could learn a thing or two from this.",
    "Men really do have worse handwriting than women – who also tend to write faster than men. It’s all to do with how we’re brought up.",
    "You shouldn't stop your dog from eating poo. Doing so makes the dog think it’s important – so it will try to tuck into a turd again, as gross as that is.",
    "There’s a 1,200km2 area of France that’s completely sealed off to the public. The First World War battlefields in the region known as the Zone Rouge are still littered with ammunition.",
    "Medieval war horses were hilariously small – basically no bigger than ponies today. On the plus side, it was easier to get back on them if you were knocked off.",
    "Bull semen can sell for tens of thousands of pounds per millilitre: it’s called white gold for a reason. The only challenge is keeping it at -196°C (-320°F) to prevent it from spoiling.",
    "There’s a worm that can survive being boiled alive. What’s even stranger is that it doesn’t seem to mind – in fact, it seems to thrive in this environment.",
    "There are earthquakes in the sky, and no-one knows why they happen. They probably come from somewhere in the atmosphere, but wherever they come from, they’re loud.",
    "You’ve never actually touched anything in your life, unless you mean in the emotional sense. In fact, you’ve been repelled by everything you’ve ever got close to.",
    "If you smell of nail polish remover, you may want to go to the doctor. It may be a sign of diabetes – and there are other ways your odour can hint at health issues.",
    "It takes 4.18 years to get over an ex, on average – although it can take longer.",
    "People are walking faster than they used to – in fact, about 15 per cent faster now than they did in 1980. The reason why is still a bit of a mystery, however.",
    "Scientists once managed to levitate a frog. Not just for fun, of course – the experiment using magnets could have plenty of other uses.",
    "A man once survived for 555 days without a heart. And another was found to be living with 90 per cent of his brain missing. It all proves we can sometimes survive while missing important organs.",
    "Without whale wee, our oceans might collapse: it helps move crucial nutrients around the world through what’s known as the Great Whale Conveyor Belt. ",
    "Roughly one in 100 children have a different biological father than they thought. That’s from two studies in Sweden and the Netherlands – another in the US put the figure as high as seven per cent.",
    "If a snake ate you, only your hair and nails would be left – that’s because they can’t process the keratin protein. Oh, it also wouldn’t be able to digest your clothes.",
    "Horseshoe crabs have blue blood, and it has helped save plenty of human lives. So we owe a big debt of gratitude to these creatures that have been around for 450 million years.",
    "You’ll spend about three and a half years of your life blinking (if you live to 80, that is). Over a 16-hour day, you’ll blink 11,520 times – the equivalent of an hour.",
    "There are stone circles that are older than Stonehenge – including one in Australia that’s about 10,000 years old. But there may be one at the bottom of a US lake that’s more than 15,000 years old…",
    "Mummies smell woody, spicy and a bit sweet. That’s according to historians at the Egyptian Museum in Cairo, who are planning to recreate the smell for visitors. Don’t all rush at once.",
    "An hour of walking burns just 250 calories. That's for the average person, and there are – ahem – steps you can take to up the ante. For instance, taking on an incline of five per cent will increase the metabolic cost of walking by 17 per cent, while a 10 per cent incline increases it by 32 per cent. You could even wear a weighted rucksack if you really want to push yourself.",
    "It's impossible to swallow your own tongue. But a myth to the contrary has led to several deaths, as first-aiders attempt to prevent people in a health crisis from swallowing their own tongues, and as such delay important interventions.",
    "Some insects can live for decades. In fact, the longest-living insect is the golden jewel beetle (Buprestis aurulenta), which can survive well into its 40s.",
    "The deepest part of the ocean reaches more than 10,900m. That's 35,700ft deep. It's called the Challenger Deep, which is the lowest point on the Mariana Trench: the narrow pinch point where the Pacific tectonic plate churns its way back into the mantle beneath.",
    "It is impossible for most people to lick their own elbow. (try it!)",
    "A crocodile cannot stick its tongue out.",
    "A shrimp's heart is in its head.",
    "It is physically impossible for pigs to look up into the sky.",
    "The \"sixth sick sheik's sixth sheep's sick\" is believed to be the toughest tongue twister in the English language.",
    "If you sneeze too hard, you could fracture a rib.",
    "Wearing headphones for just an hour could increase the bacteria in your ear by 700 times.",
    "In the course of an average lifetime, while sleeping you might eat around 70 assorted insects and 10 spiders, or more.",
    "Some lipsticks contain fish scales.",
    "Cat urine glows under a black-light.",
    "Like fingerprints, everyone's tongue print is different.",
    "Rubber bands last longer when refrigerated.",
    "There are 293 ways to make change for a dollar.",
    "The average person's left hand does 56% of the typing (when using the proper position of the hands on the keyboard; Hunting and pecking doesn't count!).",
    "A shark is the only known fish that can blink with both eyes.",
    "The longest one-syllable words in the English language are \"scraunched\" and \"strengthed.\" Some suggest that \"squirreled\" could be included, but squirrel is intended to be pronounced as two syllables (squir-rel) according to most dictionaries. \"Screeched\" and \"strengths\" are two other long one-syllable words, but they only have 9 letters.",
    "\"Dreamt\" is the only English word that ends in the letters \"mt\".",
    "Almonds are a member of the peach family.",
    "Maine is the only state that has a one-syllable name.",
    "There are only four words in the English language which end in \"dous\": tremendous, horrendous, stupendous, and hazardous.",
    "Los Angeles' full name is \"El Pueblo de Nuestra Senora la Reina de los Angeles de Porciuncula\"",
    "A cat has 32 muscles in each ear.",
    "An ostrich's eye is bigger than its brain.",
    "Tigers have striped skin, not just striped fur.",
    "In many advertisements, the time displayed on a watch is 10:10.",
    "The characters Bert and Ernie on Sesame Street were named after Bert the cop and Ernie the taxi driver in Frank Capra's \"It's a Wonderful Life.\"",
    "A dime has 118 ridges around the edge.",
    "The giant squid has the largest eyes in the world.",
    "Most people fall asleep in seven minutes.",
    "\"Stewardesses\" is the longest word that is typed with only the left hand."]